<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Alexaka1.Analyzers.StructuredLogging.Comparison</RootNamespace>
    <AssemblyName>Alexaka1.Analyzers.StructuredLogging.Comparison</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="NLog" Version="5.5.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="ZLogger" Version="1.7.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Alexaka1.Analyzers.StructuredLogging\Analyzer.csproj" />
  </ItemGroup>
</Project>
