<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <RunAnalyzers>false</RunAnalyzers>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <EnableStructuredLoggingAnalyzers Condition="'$(EnableStructuredLoggingAnalyzers)' == ''">false</EnableStructuredLoggingAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="ZLogger" Version="1.7.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="PropertiesNamingAnalyzer_SerilogInvalidSyntax.cs" />
    <None Include="PropertiesNamingAnalyzer_SerilogInvalidSyntax.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(EnableStructuredLoggingAnalyzers)' == 'true'">
    <ProjectReference Include="..\..\..\src\Alexaka1.Analyzers.StructuredLogging\Analyzer.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
