using Alexaka1.Analyzers.StructuredLogging.Tests.Infrastructure;

using Xunit;

namespace Alexaka1.Analyzers.StructuredLogging.Tests.SourceGenerated;

public sealed class GeneratedCodeSkipTests
{
    [Fact]
    public Task Non_razor_generated_trees_are_ignored_while_user_code_is_still_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            using Microsoft.Extensions.Logging;
                            public static class User
                            {
                                public static void Log(ILogger logger) =>
                                    logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                            }
                            """,
            additionalSources: new[]
            {
                ("Microsoft.Extensions.Logging.Generators/LoggerMessage.g.cs",
                    ViolatingGeneratedClass("LoggerMessageGenerated")),
                ("Something.g.i.cs", ViolatingGeneratedClass("GeneratedInterface")),
                ("Foo.generated.cs", ViolatingGeneratedClass("DotGenerated")),
                ("Form1.Designer.cs", ViolatingGeneratedClass("Designer")),
                ("App.AssemblyAttributes.cs", ViolatingGeneratedClass("AssemblyAttributes")),
                ("TemporaryGeneratedFile_abcdef.cs", ViolatingGeneratedClass("TemporaryGenerated")),
                ("HeaderOnly.cs", ViolatingGeneratedClass("HeaderOnly", header: "// <auto-generated/>")),
                ("AutogeneratedHeader.cs",
                    ViolatingGeneratedClass("AutogeneratedHeader", header: "// <autogenerated/>")),
            });
    }

    [Fact]
    public Task Generated_g_cs_without_header_is_ignored_by_path()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            using Microsoft.Extensions.Logging;
                            public static class User
                            {
                                public static void Log(ILogger logger) =>
                                    logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                            }
                            """,
            additionalSources: new[]
            {
                ("LoggerMessage.g.cs", ViolatingGeneratedClass("PathOnlyGenerated", header: null))
            });
    }

    [Fact]
    public Task Generated_code_editorconfig_skips_ordinary_cs()
    {
        return AnalyzerTestHost.VerifyAsync(
            ViolatingGeneratedClass("EditorConfigGenerated", header: null),
            editorConfig: "generated_code = true",
            sourcePath: "/0/Generated.cs");
    }

    private static string ViolatingGeneratedClass(string className, string? header = "// <auto-generated/>")
    {
        var prefix = string.IsNullOrEmpty(header) ? string.Empty : header + "\n";
        return prefix + /*lang=csharp*/ $$"""
                                          using Microsoft.Extensions.Logging;
                                          public static class {{className}}
                                          {
                                              public static void Log(ILogger logger) =>
                                                  logger.LogInformation("Hello {generatedName}.", "x");
                                          }
                                          """;
    }
}
