using Alexaka1.Analyzers.StructuredLogging.Recognition;
using Alexaka1.Analyzers.StructuredLogging.Tests.Infrastructure;

using Xunit;

namespace Alexaka1.Analyzers.StructuredLogging.Tests.SourceGenerated;

public sealed class RazorGeneratedAnalyzerTests
{
    [Theory]
    [InlineData("Components_Pages_Home_razor.g.cs", true)]
    [InlineData(@"C:\proj\obj\Home.razor.g.cs", true)]
    [InlineData(@"C:\proj\obj\Home.razor.ABC123.ide.g.cs", true)]
    [InlineData(@"C:\proj\obj\Home.razor__virtual.cs", true)]
    [InlineData("Pages_Index_cshtml.g.cs", true)]
    [InlineData("Index.cshtml.g.cs", true)]
    [InlineData("LoggerMessage.g.cs", false)]
    [InlineData("Home.razor.cs", false)]
    [InlineData("Test.cs", false)]
    [InlineData("", false)]
    [InlineData(null, false)]
    public void Razor_source_generated_file_detection(string? path, bool expected)
    {
        Assert.Equal(expected, GeneratedCode.IsRazorSourceGeneratedFile(path));
    }

    [Theory]
    [InlineData("LoggerMessage.g.cs", true)]
    [InlineData("Foo.generated.cs", true)]
    [InlineData("Something.g.i.cs", true)]
    [InlineData("Form1.Designer.cs", true)]
    [InlineData("App.AssemblyAttributes.cs", true)]
    [InlineData("TemporaryGeneratedFile_abcdef.cs", true)]
    [InlineData("Components_Pages_Home_razor.g.cs", false)]
    [InlineData("Home.razor.g.cs", false)]
    [InlineData("Home.razor.cs", false)]
    [InlineData("Test.cs", false)]
    public void Generated_file_path_does_not_treat_razor_as_skippable(string path, bool expected)
    {
        Assert.Equal(expected, GeneratedCode.IsGeneratedFilePath(path));
    }

    [Fact]
    public Task Razor_g_cs_with_auto_generated_header_is_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            // <auto-generated/>
                            using Microsoft.Extensions.Logging;
                            public partial class Home
                            {
                                private readonly ILogger<Home> _logger = null!;
                                public void OnInitialized()
                                {
                                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                                }
                            }
                            """,
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_with_generated_code_editorconfig_is_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            // <auto-generated/>
                            using Microsoft.Extensions.Logging;
                            public partial class Home
                            {
                                private readonly ILogger<Home> _logger = null!;
                                public void OnInitialized()
                                {
                                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                                }
                            }
                            """,
            editorConfig: "generated_code = true",
            sourcePath:
            "/0/generated/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Dot_razor_g_cs_hint_name_is_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            // <auto-generated/>
                            using Microsoft.Extensions.Logging;
                            public partial class Home
                            {
                                private readonly ILogger<Home> _logger = null!;
                                public void OnInitialized()
                                {
                                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                                }
                            }
                            """,
            sourcePath: "Home.razor.g.cs");
    }

    [Theory]
    [InlineData("Home.razor.ABC123.ide.g.cs", true)]
    [InlineData("Home.razor__virtual.cs", true)]
    [InlineData("Foo.g.cs", false)]
    public async Task Design_time_razor_documents_are_analyzed(string sourcePath, bool expectDiagnostic)
    {
        const string source = /*lang=csharp*/ """
                                              // <auto-generated/>
                                              using Microsoft.Extensions.Logging;
                                              public partial class Home
                                              {
                                                  private readonly ILogger<Home> _logger = null!;
                                                  public void OnInitialized()
                                                  {
                                                      _logger.LogInformation("Hello {name}", "world");
                                                  }
                                              }
                                              """;

        var diagnostics = await AnalyzerTestHost.GetDiagnosticsAsync(source, sourcePath: sourcePath);
        Assert.Equal(expectDiagnostic, diagnostics.Any(diagnostic => diagnostic.Id == "AASL0009"));
    }

    [Fact]
    public Task Cshtml_g_cs_is_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            // <auto-generated/>
                            using Microsoft.Extensions.Logging;
                            public partial class Index
                            {
                                private readonly ILogger<Index> _logger = null!;
                                public void OnGet()
                                {
                                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                                }
                            }
                            """,
            sourcePath: "Pages_Index_cshtml.g.cs");
    }

    [Fact]
    public Task Razor_cs_code_behind_is_analyzed()
    {
        return AnalyzerTestHost.VerifyAsync(
            /*lang=csharp*/ """
                            using Microsoft.Extensions.Logging;
                            public partial class Counter
                            {
                                private readonly ILogger<Counter> _logger = null!;
                                public void OnInitialized()
                                {
                                    _logger.LogInformation("Clicked {|AASL0009:{count}|}{|AASL0011:.|}", 1);
                                }
                            }
                            """,
            sourcePath: "/0/Components/Pages/Counter.razor.cs");
    }
}
