using Alexaka1.Analyzers.StructuredLogging.CodeFixes;
using Alexaka1.Analyzers.StructuredLogging.Tests.Infrastructure;
using Xunit;

namespace Alexaka1.Analyzers.StructuredLogging.Tests.SourceGenerated;

public sealed class RazorGeneratedFixTests
{
    [Fact]
    public Task Razor_cs_renames_template_property()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            using Microsoft.Extensions.Logging;
            public partial class Counter
            {
                private readonly ILogger<Counter> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Clicked {|AASL0009:{count}|}", 1);
                }
            }
            """,
            /*lang=csharp*/ """
            using Microsoft.Extensions.Logging;
            public partial class Counter
            {
                private readonly ILogger<Counter> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Clicked {Count}", 1);
                }
            }
            """,
            "AASL0009",
            typeof(RenameTemplatePropertyCodeFixProvider),
            sourcePath: "/0/Components/Pages/Counter.razor.cs");
    }

    [Fact]
    public Task Razor_cs_removes_trailing_period()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            using Microsoft.Extensions.Logging;
            public partial class Counter
            {
                private readonly ILogger<Counter> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Clicked {Count}{|AASL0011:.|}", 1);
                }
            }
            """,
            /*lang=csharp*/ """
            using Microsoft.Extensions.Logging;
            public partial class Counter
            {
                private readonly ILogger<Counter> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Clicked {Count}", 1);
                }
            }
            """,
            "AASL0011",
            typeof(RemoveTrailingPeriodCodeFixProvider),
            sourcePath: "/0/Components/Pages/Counter.razor.cs");
    }

    [Fact]
    public Task Razor_g_cs_renames_template_property()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}", "world");
                }
            }
            """,
            "AASL0009",
            typeof(RenameTemplatePropertyCodeFixProvider),
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_with_generated_code_editorconfig_renames_template_property()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}", "world");
                }
            }
            """,
            "AASL0009",
            typeof(RenameTemplatePropertyCodeFixProvider),
            editorConfig: "generated_code = true",
            sourcePath: "/0/generated/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_removes_trailing_period()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}{|AASL0011:.|}", "world");
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}", "world");
                }
            }
            """,
            "AASL0011",
            typeof(RemoveTrailingPeriodCodeFixProvider),
            sourcePath: "Home.razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_converts_interpolation()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation({|AASL0007:$"Hello {name}"|});
                }
                private string name = "world";
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}", name);
                }
                private string name = "world";
            }
            """,
            "AASL0007",
            typeof(ConvertInterpolatedTemplateCodeFixProvider),
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_renames_positional_placeholder()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized(string userId)
                {
                    _logger.LogInformation("Hello {|AASL0008:{0}|}", userId);
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized(string userId)
                {
                    _logger.LogInformation("Hello {UserId}", userId);
                }
            }
            """,
            "AASL0008",
            typeof(RenameTemplatePropertyCodeFixProvider),
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_adds_destructuring()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Serilog;
            public partial class Home
            {
                public void OnInitialized()
                {
                    Log.Logger.Information("{|AASL0001:{MyProperty}|}", new { Test = 1 });
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Serilog;
            public partial class Home
            {
                public void OnInitialized()
                {
                    Log.Logger.Information("{@MyProperty}", new { Test = 1 });
                }
            }
            """,
            "AASL0001",
            typeof(AddDestructuringCodeFixProvider),
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }

    [Fact]
    public Task Cshtml_g_cs_renames_template_property()
    {
        return AnalyzerTestHost.VerifyFixAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Index
            {
                private readonly ILogger<Index> _logger = null!;
                public void OnGet()
                {
                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Index
            {
                private readonly ILogger<Index> _logger = null!;
                public void OnGet()
                {
                    _logger.LogInformation("Hello {Name}", "world");
                }
            }
            """,
            "AASL0009",
            typeof(RenameTemplatePropertyCodeFixProvider),
            sourcePath: "Pages_Index_cshtml.g.cs");
    }

    [Fact]
    public Task Razor_g_cs_fix_all_renames_template_properties()
    {
        return AnalyzerTestHost.VerifyFixAllAsync(
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {|AASL0009:{name}|}", "world");
                    _logger.LogInformation("Clicked {|AASL0009:{count}|}", 1);
                }
            }
            """,
            /*lang=csharp*/ """
            // <auto-generated/>
            using Microsoft.Extensions.Logging;
            public partial class Home
            {
                private readonly ILogger<Home> _logger = null!;
                public void OnInitialized()
                {
                    _logger.LogInformation("Hello {Name}", "world");
                    _logger.LogInformation("Clicked {Count}", 1);
                }
            }
            """,
            "AASL0009",
            typeof(RenameTemplatePropertyCodeFixProvider),
            sourcePath: "Components_Pages_Home_razor.g.cs");
    }
}
