using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Alexaka1.Analyzers.StructuredLogging.Recognition;

internal static class GeneratedCode
{
    public static bool IsGenerated(SyntaxTree tree, AnalyzerOptions options)
    {
        // Razor/Blazor @code is compiled to *_razor.g.cs (and *_cshtml.g.cs).
        // Those trees are marked generated, but #line maps back to user .razor
        // source. Analyze them; still skip LoggerMessage.g.cs and peers.
        if (IsRazorSourceGeneratedFile(tree.FilePath))
        {
            return false;
        }

        if (options.AnalyzerConfigOptionsProvider.GetOptions(tree).TryGetValue("generated_code", out var value) &&
            (string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ||
             string.Equals(value, "yes", StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        if (IsGeneratedFilePath(tree.FilePath))
        {
            return true;
        }

        return HasAutoGeneratedHeader(tree);
    }

    public static bool IsRazorSourceGeneratedFile(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath))
        {
            return false;
        }

        var fileName = Path.GetFileName(filePath);
        if (!fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) &&
            !fileName.EndsWith("__virtual.cs", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        return HasMarkerWithBoundary(fileName, ".razor") ||
               HasMarkerWithBoundary(fileName, "_razor") ||
               HasMarkerWithBoundary(fileName, ".cshtml") ||
               HasMarkerWithBoundary(fileName, "_cshtml");
    }

    public static bool IsGeneratedFilePath(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath))
        {
            return false;
        }

        if (IsRazorSourceGeneratedFile(filePath))
        {
            return false;
        }

        var fileName = Path.GetFileName(filePath);
        if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasMarkerWithBoundary(string fileName, string marker)
    {
        var searchStart = 0;
        while (searchStart < fileName.Length)
        {
            var markerIndex = fileName.IndexOf(marker, searchStart, StringComparison.OrdinalIgnoreCase);
            if (markerIndex < 0)
            {
                return false;
            }

            var boundaryIndex = markerIndex + marker.Length;
            if (boundaryIndex < fileName.Length &&
                (fileName[boundaryIndex] == '.' || fileName[boundaryIndex] == '_'))
            {
                return true;
            }

            searchStart = markerIndex + 1;
        }

        return false;
    }

    private static bool HasAutoGeneratedHeader(SyntaxTree tree)
    {
        var text = tree.GetText();
        if (text.Length == 0)
        {
            return false;
        }

        var length = Math.Min(text.Length, 400);
        var header = text.GetSubText(new TextSpan(0, length)).ToString();
        return header.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0 ||
               header.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0;
    }
}
