using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Alexaka1.Analyzers.StructuredLogging.Recognition;

internal static class GeneratedCode
{
    public static bool IsGenerated(SyntaxTree tree, AnalyzerOptions options)
    {
        if (options.AnalyzerConfigOptionsProvider.GetOptions(tree).TryGetValue("generated_code", out var value) &&
            (string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ||
             string.Equals(value, "yes", StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        if (IsGeneratedFilePath(tree.FilePath))
        {
            return true;
        }

        return HasAutoGeneratedHeader(tree);
    }

    public static bool IsGeneratedFilePath(string? filePath)
    {
        if (string.IsNullOrEmpty(filePath))
        {
            return false;
        }

        var fileName = Path.GetFileName(filePath);
        if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
               fileName.EndsWith(".AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(SyntaxTree tree)
    {
        var text = tree.GetText();
        if (text.Length == 0)
        {
            return false;
        }

        var length = Math.Min(text.Length, 400);
        var header = text.GetSubText(new TextSpan(0, length)).ToString();
        return header.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0 ||
               header.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0;
    }
}
